### ISSUE TITLE
Environment/configuration problems since 10.0.10

### ISSUE THREAD

**Issue by daniel-lerch** [owncloud-docker/server#108]
When you update from ownCloud 10.0.8 to 10.0.10 without changing any configuration, your installation won't work anymore. Changing the port from `80` to `8080` without notice is an absolute no-go for a servicing release. However the much more severe problem is associated with environment variables. In order to be able to use `occ` with version 10.0.10 I had to add the following default environment variables explicitly to my _docker-compose.yml_ file:

- `OWNCLOUD_DB_PREFIX=oc_`
- `OWNCLOUD_VOLUME_APPS=/mnt/data/apps`
- `OWNCLOUD_VOLUME_CONFIG=/mnt/data/config`
- `OWNCLOUD_VOLUME_FILES=/mnt/data/files`
- `OWNCLOUD_VOLUME_ROOT=/mnt/data`
- `OWNCLOUD_VOLUME_SESSIONS=/mnt/data/sessions`

It seems like `occ` is unable to read the `config.php` which was configured properly for more than a year.

### System Information ###
Intel Core i3-3217U
4GB DDR3 RAM
Ubuntu Server 18.04.1 LTS
Docker version 18.09.0, build 4d60db4
docker-compose version 1.23.1, build b02f1306

### Compose file ###
```yaml
version: '2.1'

services:
  app:
    image: owncloud/server:10.0.10
    restart: unless-stopped
    ports:
      - 10501:8080
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_SUB_URL=${OWNCLOUD_SUB_URL}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
#      - OWNCLOUD_DB_PREFIX=oc_
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
#      - OWNCLOUD_VOLUME_APPS=/mnt/data/apps
#      - OWNCLOUD_VOLUME_CONFIG=/mnt/data/config
#      - OWNCLOUD_VOLUME_FILES=/mnt/data/files
#      - OWNCLOUD_VOLUME_ROOT=/mnt/data
#      - OWNCLOUD_VOLUME_SESSIONS=/mnt/data/sessions
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/files:/mnt/data

  db:
    image: webhippie/mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: unless-stopped
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/redis:/var/lib/redis
```
