### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'172.25.0.4'

### ISSUE THREAD

**Issue by pieterhouwen** [owncloud-docker/server#266]
When using the default docker-compose.yml I get the following errors:

# MariaDB logs
```
mariadb_1   | 2021-10-19 22:16:37 0 [Warning] 'proxies_priv' entry '@% root@10c596339342' ignored in --skip-name-resolve mode.
mariadb_1   | 2021-10-19 22:16:37 0 [ERROR] Incorrect definition of table mysql.event: expected column 'definer' at position 3 to have type char(, found type varchar(384).
mariadb_1   | 2021-10-19 22:16:37 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
mariadb_1   | 2021-10-19 22:16:37 0 [Note] Reading of all Master_info entries succeeded
mariadb_1   | 2021-10-19 22:16:37 0 [Note] Added new Master_info '' to hash table
mariadb_1   | 2021-10-19 22:16:37 0 [Note] mysqld: ready for connections.
mariadb_1   | Version: '10.5.12-MariaDB-1:10.5.12+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb_1   | 2021-10-19 22:16:39 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.25.0.4' (This connection closed normally without authentication)
mariadb_1   | 2021-10-19 22:16:40 4 [Warning] Access denied for user 'owncloud'@'172.25.0.4' (using password: YES)
mariadb_1   | 2021-10-19 22:16:43 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '172.25.0.4' (This connection closed normally without authentication)
mariadb_1   | 2021-10-19 22:16:43 6 [Warning] Access denied for user 'owncloud'@'172.25.0.4' (using password: YES)
mariadb_1   | 2021-10-19 22:16:45 7 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
mariadb_1   | 2021-10-19 22:16:47 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.25.0.4' (This connection closed normally without authentication)
mariadb_1   | 2021-10-19 22:16:48 9 [Warning] Access denied for user 'owncloud'@'172.25.0.4' (using password: YES)
mariadb_1   | 2021-10-19 22:16:53 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.25.0.4' (This connection closed normally without authentication)
```

# owncloud_server logs
```
owncloud_server | Creating volume folders...
owncloud_server | Creating hook folders...
owncloud_server | Waiting for MySQL...
owncloud_server | services are ready!
owncloud_server | Waiting for Redis...
owncloud_server | services are ready!
owncloud_server | Removing custom folder...
owncloud_server | Linking custom folder...
owncloud_server | Removing config folder...
owncloud_server | Linking config folder...
owncloud_server | Writing config file...
owncloud_server | Fixing base perms...
owncloud_server | Fixing data perms...
owncloud_server | Fixing hook perms...
owncloud_server | Installing server database...
owncloud_server | Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'172.25.0.4' (using password: YES)
owncloud_server |  ->
```

# .ENV file
```
OWNCLOUD_VERSION=10.8
OWNCLOUD_DOMAIN=localhost:8080
ADMIN_USERNAME=admin
ADMIN_PASSWORD=SuperSecurePasswordNobodyWillEverGuess
HTTP_PORT=8080
```

# docker-compose.yml
```
version: "3"

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
```

I really have no idea how to fix this.
