### ISSUE TITLE
Force https using owncloud/server:10.0.3

### ISSUE THREAD

**Issue by s-geissler** [owncloud-docker/server#30]
I am running owncloud/server:latest and am looking for a way to force https (i.e. redirect all port 80 requests to 443).

Is there a way without building a custom image on top of owncloud/server that configures the redirect via apache?

**Comment by tboerger** [comment]
There is no option for that yet, most people are anyway running it behind a reverse proxy that handles the SSL termination and SSL enforcement.

**Comment by sfmarques** [comment]
i use [reverse proxy]( https://github.com/jwilder/nginx-proxy ) and it does the job

**Comment by s-geissler** [comment]
Could you help me out here? Below are the two docker-compose files I am using to start the nginx-proxy as well as owncloud. I am obviously missing something as I only get 503 when connecting on port 80 and nothing at all on port 443.

```
version: '3'

services:
  owncloud:
    image: owncloud/server:${VERSION}
    restart: always
#  ports:
#      - ${HTTPS_PORT}:443
#      - ${HTTP_PORT}:80
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - VIRTUAL_HOST=owncloud.domain.de
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/mnt/data

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_MAXCONN=10000
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./redis:/var/lib/redis
```

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```
