### ISSUE TITLE
unable to run with independent database

### ISSUE THREAD

**Issue by skironDotNet** [owncloud-docker/server#356]
I tested the boiler place docker-compose and runs fine, but I need to migrate old DB from OC 10.5 and want to run o single shared mysql instance docker

I also didn't want to use docker volumes but local folders so my volume mount is at `./data/cloud` so folder where compose file is
I needed to `chown -R wwwd-data:root data/cloud` to make it start, and worked fine as full stack OC + Maria + Redis
Now I wanted to remove maria from this stack, and BTW my mysql runs on the same docker network named `npmnet` so connection should not be a problem

here is my compose
```
version: "3"

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=cloud_temp
      - OWNCLOUD_DB_USERNAME=temp_user
      - OWNCLOUD_DB_PASSWORD=some-pwd
      - OWNCLOUD_DB_HOST=mysql
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/cloud:/mnt/data
    network_mode: npmnet

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/redis:/data
    network_mode: npmnet
```
and when run docker-compose this is my output like it hanged. I did clear old containers before, the ./data folders har right permission etc.
Why output writes 'Waiting on MySQL` when there is no depend on 
![image](https://user-images.githubusercontent.com/2981715/208182035-35efae85-38f7-45f9-81e6-f6675f229622.png)
