### ISSUE TITLE
Server fails to write crash file

### ISSUE THREAD

**Issue by mybuntu-git2** [owncloud-docker/server#384]
Thanks for your help I am really stuck at this point.
I have an OC docker image (latest) with data folder mounted and permissions set to 777 and external redis and mariadb. I run it on an Odroid N2+ (arm) Ubuntu 22.04 headless as root.
I start the container with docker-compose (details at the end) and the server starts correctly but then when attempting access it crashes due to permission to write php crash files.

 docker log until crash:
```
root@odroid:/home/owncloud# docker logs owncloud_server
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
services are ready!
Waiting for Redis...
services are ready!
Removing custom folder...
Linking custom folder...
Removing config folder...
Linking config folder...
Writing config file...
Fixing base perms...
Fixing data perms...
Fixing hook perms...
Upgrading server database...
Writing objectstore config...
Writing php config...
Updating htaccess config...
Writing apache config...
Enabling cron background...
Writing crontab file...
Touching cron configs...
Starting cron daemon...
Starting apache daemon...
[Sat Mar 25 07:41:34.713959 2023] [mpm_prefork:notice] [pid 122] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Sat Mar 25 07:41:34.714055 2023] [core:notice] [pid 122] AH00094: Command line: '/usr/sbin/apache2 -f /etc/apache2/apache2.conf -D FOREGROUND'
127.0.0.1 - - [25/Mar/2023:07:42:00 +0000] "GET /status.php HTTP/1.1" 200 303 "-" "curl/7.68.0"
[Sat Mar 25 07:42:17.725423 2023] [php7:warn] [pid 123] [client 10.8.0.6:50858] PHP Warning:  file_put_contents(/var/www/owncloud/data/crash-2023-03-25.log): failed to open stream: No such file or directory in /var/www/owncloud/lib/base.php on line 1038
[Sat Mar 25 07:42:17.725523 2023] [php7:warn] [pid 123] [client 10.8.0.6:50858] PHP Warning:  file_put_contents(/var/www/owncloud/data/crash-2023-03-25.log): failed to open stream: No such file or directory in /var/www/owncloud/lib/base.php on line 1038
10.8.0.6 - - [25/Mar/2023:07:42:17 +0000] "GET / HTTP/1.1" 599 363 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1"
```

this is the compose file:
```
version: "3"

services:
  owncloud:
    image: owncloud/server:latest
    deploy:
      resources:
        limits:
         cpus: '3'
         memory: 800M
    container_name: owncloud_server
    #restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - HTTP_PORT=8080
      - OWNCLOUD_DOMAIN=192.168.17.3
      - OWNCLOUD_TRUSTED_DOMAINS=localhost,192.168.17.1,192.168.100.1,192.168.1.1,10.8.0.1,0.0.0.0
      - OWNCLOUD_TRUSTED_PROXIES=192.168.17.3
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud_docker_1
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=mypass
      - OWNCLOUD_DB_HOST=192.168.17.3
      - OWNCLOUD_ADMIN_USERNAME=myuser
      - OWNCLOUD_ADMIN_PASSWORD=mypassword
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=192.168.17.3
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/owncloud/docker_mnt/data:/mnt/data
```

 I verified and there is no crash file under data persistent folder, and I run the compose as root. As long as I do not attempt accessing the webui, the server is up and running.
