### ISSUE TITLE
Unable to start with NFS storage: Cannot write into "config" directory

### ISSUE THREAD

**Issue by axelrindle** [owncloud-docker/server#394]
### The Problem

I want to move my local ownCloud installation to a dockerized deployment using the following `docker-compose.yml`:

<details>
<summary><code>docker-compose.yml</code></summary>

```
version: "3.9"

services:
  redis:
    image: redis:7

  server:
    image: owncloud/server:10.11
    depends_on:
      - redis
    volumes:
      - owncloud_data:/mnt/data
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
    environment:
      - OWNCLOUD_SECRET="example"
      - OWNCLOUD_CIPHER="AES-256-CFB"
      - OWNCLOUD_DOMAIN="cloud.example.org"
      - OWNCLOUD_MAX_UPLOAD="100G"
      - OWNCLOUD_DB_TYPE="mysql"
      - OWNCLOUD_DB_HOST="/run/mysqld/mysqld.sock"
      - OWNCLOUD_DB_NAME="owncloud"
      - OWNCLOUD_DB_USERNAME="owncloud"
      - OWNCLOUD_DB_PASSWORD="example"
      - OWNCLOUD_DB_PREFIX="oc_"
      - OWNCLOUD_MYSQL_UTF8MB4="true"
      - OWNCLOUD_REDIS_ENABLED="true"
      - OWNCLOUD_MEMCACHE_LOCAL="\\OC\\Memcache\\Redis"
      - OWNCLOUD_DEFAULT_LANGUAGE="de"
      - OWNCLOUD_LOG_TIMEZONE="Europe/Berlin"
      - OWNCLOUD_LOG_DATE_FORMAT="F d, Y H:i:s"
      - OWNCLOUD_LOG_LEVEL="2"
      - OWNCLOUD_VERSION_HIDE="true"
      - OWNCLOUD_SHOW_SERVER_HOSTNAME="false"
      - OWNCLOUD_MAIL_SMTP_PASSWORD=""
      - OWNCLOUD_CORS_ALLOWED_DOMAINS="cloud.example.org"
      - OWNCLOUD_SKIP_CHOWN=true
      - OWNCLOUD_SKIP_CHMOD=true
    deploy:
      restart_policy:
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.http.routers.cloud.entrypoints=http
        - traefik.http.routers.cloud.rule=Host(`cloud.example.org`)
        - traefik.http.services.cloud.loadbalancer.server.port=8080

volumes:
  owncloud_data:
    external: true

networks:
  traefik:
    external: true

```

</details>

Deploying that results in the following error:

```
Creating volume folders...
Creating hook folders...
Writing config file...
Skipping chown as requested...
Skipping chmod as requested...
Installing server database...
Cannot write into "config" directory
This can usually be fixed by <a href="https://doc.owncloud.com/server/10.12/go.php?to=admin-dir_permissions" target="_blank" rel="noreferrer">giving the webserver write access to the config directory</a>.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /var/www/owncloud/lib/private/Console/Application.php:139
Stack trace:
#0 /var/www/owncloud/console.php(115): OC\Console\Application->loadCommands()
#1 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#2 {main}
```

I do not quite understand what component cannot write to the config directory and why. When doing an `ls` in the data directory, I can see some directories have been created, e.g. `config` and `files`. There are even files in there.

### Additional Information

The NFS Server is a Synology Diskstation with the following configuration:

![grafik](https://github.com/owncloud-docker/server/assets/7105632/a01987a9-dfa6-4d99-a8c1-3a31b5484db5)

Root is mapped to the admin user to allow Docker to mount the share as Docker runs as root.

Doing an `ls -lA` inside the mounted NFS share produces:

```
www-data@81954111aab7:~/owncloud$ ls -Al /mnt/data/
total 192
d--------- 1 root     root        346 May 18 21:21 '#recycle'
drwxrwxrwx 1 www-data www-data      0 May 18 21:25  apps
drwxrwxrwx 1 www-data www-data     60 May 18 21:25  config
drwxrwxrwx 1 www-data www-data     24 May 18 21:25  files
drwxrwxrwx 1 www-data www-data      0 May 18 21:25  sessions
```

The file `config/config.php` is empty...

### Related Issues

I checked the issues #3 and #71.
