### ISSUE TITLE
owncloud_owncloud_1 keeps restarting with bind mount

### ISSUE THREAD

**Issue by maxkomarychev** [owncloud-docker/server#58]
owncloud_owncloud_1 keeps restarting when I try to use bind mount here:https://github.com/owncloud-docker/server/blob/master/docker-compose.yml#L41
either with syntax 

```
    volumes:
      - ./files:/mnt/data
```
or

```
    volumes:
      - type: bind
        source: ./files
        target: /mnt/data
```

the status is keeping in "starting" for ~5 sec and then goes into restarting, and then loops infinitely in starting->restarting.

Is there a way to launch owncloud with `bind` mount?
