### ISSUE TITLE
new volume behaviour when migrating from owncloud 9 to 10

### ISSUE THREAD

**Issue by arielelkin** [owncloud-docker/server#67]
I notice that the latest official [`docker-compose.yml` ](https://raw.githubusercontent.com/owncloud-docker/server/master/docker-compose.yml) mounts the volume containing the owncloud files thus:

```
services:
  owncloud:
    volumes:
      - files:/mnt/data
```

Currently, my owncloud files are also on a host directory mounted on the owncloud container:

```
version: '2'

services:
  owncloud:
    image: owncloud:9.1
    container_name: fullbackup_owncloud
    links:
      - owncloud_db
    ports:
      - portnumber:otherportnumber
    volumes:
      - "~/fullbackup/data:/var/www/html/data"
      - "~/fullbackup/owncloud_config:/var/www/html/config"
    restart: always

  owncloud_db:
    image: mariadb
    container_name: fullbackup_db
    environment:
      MYSQL_ROOT_PASSWORD: apassword
    restart: always
```

If I
1. remove my pre-existing docker 9 and mariadb containers 
1. follow [the official installation instructions](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/) and specify

```
services:
  owncloud:
    volumes:
      - files:~/fullbackup/data
```

will I have to resync all my files?
