### ISSUE TITLE
Server database isn't installed

### ISSUE THREAD

**Issue by romashkinvi** [owncloud-docker/server#93]
Hi!
I've tried to install owncloud-docker on MacOS 10.13.6.
But installation is failed.
log:
```
owncloud_1  | Creating volume folders...
owncloud_1  | Creating hook folders...
owncloud_1  | Waiting for MySQL...
owncloud_1  | wait-for-it: waiting 180 seconds for db:3306
owncloud_1  | wait-for-it: db:3306 is available after 0 seconds
owncloud_1  | Waiting for Redis...
owncloud_1  | wait-for-it: waiting 60 seconds for redis:6379
owncloud_1  | wait-for-it: redis:6379 is available after 0 seconds
owncloud_1  | Writing config file...
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Fixing hook perms...
owncloud_1  | Installing server database...
owncloud_1  | 
owncloud_1  |                                                      
owncloud_1  |   Too many arguments, expected arguments "command".  
owncloud_1  |                                                      
owncloud_1  | 
owncloud_1  | maintenance:install [--database DATABASE] [--database-name DATABASE-NAME] [--database-host DATABASE-HOST] [--database-user DATABASE-USER] [--database-pass [DATABASE-PASS]] [--database-table-prefix [DATABASE-TABLE-PREFIX]] [--admin-user ADMIN-USER] [--admin-pass ADMIN-PASS] [--data-dir DATA-DIR]
owncloud_1  | 
```
docker-compose ps
```
              Name                             Command                  State        Ports  
--------------------------------------------------------------------------------------------
owncloud-docker-server_db_1         /usr/bin/entrypoint /bin/s ...   Up (healthy)   3306/tcp
owncloud-docker-server_owncloud_1   /usr/bin/entrypoint /usr/b ...   Restarting             
owncloud-docker-server_redis_1      /usr/bin/entrypoint /bin/s ...   Up (healthy)   6379/tcp
```
Docker version: 18.06.1-ce-mac73 (26764) stable:
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

I changed the only ports and owncloud password.

.env
```
OWNCLOUD_VERSION=10.0.10

OWNCLOUD_DOMAIN=localhost

HTTP_PORT=80
HTTPS_PORT=8943
```

docker-compose.yml:
```
version: '2.1'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    ports:
      - ${HTTP_PORT}:8980
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis
```
Can anybody help me to solve this problem?
